# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. 
on:
  release:
   types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-test:
    name: run test before deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test

  deploy-cloud-function:
    name: deploy cloud function
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build source for deployment
        id: build
        run: |
          npm install
          npm run compile
          shopt -s extglob
          rm -rf !("build"|"package.json"|".git")
      - name: Deploy a Cloud Function
        id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: your_project_name
          description: your_project_description
          runtime: nodejs14
          entry_point: app
          region: europe-west1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SECRETS }}
